spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.application.name=tms
springdoc.swagger-ui.path=/swagger-ui.html


spring.datasource.url=jdbc:mysql://localhost:3306/TMS?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456@abcd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=fdd50500942e3992acc7fcda436a46fb65d05617db26337a98685e8432d997f8
jwt.expiration=900000

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=ansh.parnami@cloudsufi.com
spring.mail.password=bsjvehywpbcxhmiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
# TURN OFF STARTTLS (since we are using SSL from the start):
spring.mail.properties.mail.smtp.starttls.enable=false